version: '3'

services:
  config-server:
      build:
        context: ./configServer
      ports:
        - 7080:7080
      volumes: 
        - ./configServer/config-server-repository:/opt/config-server-repository
  eureka-server:
      build:
        context: ./eureka_server
      ports:
        - 8761:8761
      depends_on: 
        - config-server
  microserice-cliente:
      build:
        context: ./microservice_client
      ports:
        - 7081:7081
      depends_on: 
        - eureka-server